Traceback (most recent call last):
  File "img2feat_dpt.py", line 10, in <module>
    import cv2
  File "/data/zlhu/miniconda3/envs/ldm/lib/python3.8/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
